const { withAppBuildGradle } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Injects real release signing into the generated android/app/build.gradle, reading credentials
 * from keystore/release-signing.properties (gitignored, machine-local — see .gitignore).
 *
 * Why this exists: `android/` is regenerated by `expo prebuild --clean`, which would otherwise
 * silently revert the release build type back to the default debug-keystore signing (the same
 * key/password bundled in every React Native install) every time prebuild runs. This plugin
 * re-applies the real signing config every time, so that can't happen unnoticed.
 *
 * Missing properties file or keystore → no-op (other machines/CI still build, just debug-signed).
 */

function readProps(filePath) {
  const text = fs.readFileSync(filePath, 'utf8');
  const props = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    props[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
  return props;
}

const DEBUG_SIGNING_BLOCK = `signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;

const RELEASE_BLOCK_ANCHOR = `// Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const withReleaseSigning = (config) => {
  return withAppBuildGradle(config, (config) => {
    const propsPath = path.join(config.modRequest.projectRoot, 'keystore', 'release-signing.properties');
    if (!fs.existsSync(propsPath)) {
      return config; // no keystore configured on this machine — leave default debug-signed release
    }

    const props = readProps(propsPath);
    const required = ['RELEASE_STORE_FILE', 'RELEASE_STORE_PASSWORD', 'RELEASE_KEY_ALIAS', 'RELEASE_KEY_PASSWORD'];
    if (required.some((k) => !props[k])) {
      console.warn('[withReleaseSigning] release-signing.properties is missing required keys — skipping.');
      return config;
    }

    const keystoreSrc = path.join(config.modRequest.projectRoot, 'keystore', props.RELEASE_STORE_FILE);
    if (!fs.existsSync(keystoreSrc)) {
      console.warn(`[withReleaseSigning] keystore file not found at ${keystoreSrc} — skipping.`);
      return config;
    }
    // Copy into android/app/ so Gradle's file('...') (relative to the app module dir) resolves.
    const keystoreDest = path.join(config.modRequest.platformProjectRoot, 'app', props.RELEASE_STORE_FILE);
    fs.copyFileSync(keystoreSrc, keystoreDest);

    let contents = config.modResults.contents;

    if (!contents.includes(DEBUG_SIGNING_BLOCK)) {
      console.warn('[withReleaseSigning] Expected signingConfigs block not found — skipping injection (build.gradle template may have changed).');
      return config;
    }
    const withReleaseConfig = DEBUG_SIGNING_BLOCK.replace(
      /\n\s*\}\s*$/,
      `
        release {
            storeFile file('${props.RELEASE_STORE_FILE}')
            storePassword '${props.RELEASE_STORE_PASSWORD}'
            keyAlias '${props.RELEASE_KEY_ALIAS}'
            keyPassword '${props.RELEASE_KEY_PASSWORD}'
        }
    }`,
    );
    contents = contents.replace(DEBUG_SIGNING_BLOCK, withReleaseConfig);

    if (!contents.includes(RELEASE_BLOCK_ANCHOR)) {
      console.warn('[withReleaseSigning] Release signingConfig anchor not found — signingConfigs.release was added but the release build type may still point at debug. Check build.gradle manually.');
      config.modResults.contents = contents;
      return config;
    }
    contents = contents.replace(
      RELEASE_BLOCK_ANCHOR,
      `// Release build — signed via keystore/release-signing.properties (see plugins/withReleaseSigning.js)
            signingConfig signingConfigs.release`,
    );

    config.modResults.contents = contents;
    return config;
  });
};

module.exports = withReleaseSigning;
